baseURL = "https://LivDreyer.github.io/CSS24_ProjectB"
title = "Social Informatics"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Andreas Rosenquist", "Felix Lund Frandsen", "Liv Dreyer Johansen"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/peterampazzo/project-website-template"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

