baseURL = "https://LivDreyer.github.io/CSS24_ProjectB"
title = "Social Informatics"
description = "Symphony of Data"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Andreas Rosenquist", "Felix Lund Frandsen", "Liv Dreyer Johansen"]
    notebook = "/ProjectB_final1.html"
    data = "https://github.com/LivDreyer/CSS24/blob/main/Project_B_Folder/Folder_With_All_CSV_Files.zip"
    github = "https://github.com/LivDreyer/CSS24/tree/main/Project_B_Folder"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

